### ISSUE TITLE
Update petgraph and use StableGraph

### ISSUE THREAD

**Issue by Jengamon** [mitchmindtree/daggy#12]
Hello.
I'm here, getting ready to use daggy in a project of mine, when I check Dag's documentation, and find out that removals may change indices. I looked around (docs.rs), and found that because daggy used petgraph 0.2.2, it missed out on petgraph 0.4.3's [StableGraph](https://docs.rs/petgraph/0.4.3/petgraph/stable_graph/struct.StableGraph.html).

I would like to propose updating, and building Dag off of StableGraph, in order to stablize indices.

**Comment by mitchmindtree** [comment]
@Bobhostern Something along these lines sounds great :+1: I think I'd prefer if we maintained both options somehow: the current slightly more performant option as well as a version based on `StableGraph`.

I've been thinking about this for a while and I'm still unsure what the best abstraction for this is. Personally I think I'd like to see petgraph's `Graph` be generic over the node/edge storage so that it did not require an entirely separate, almost identical API implementation just for the `StableGraph`. However I understand that this is tricky to do cleanly without something like Higher-Kinded Types. As a result, it's probably best for us to do something similar in daggy where we implement a second, `StableDag` type.

I'm slightly tempted to just switch the `Dag` to use `StableGraph` internally, however it is hard to tell how much this would impact downstream crates like `dsp-chain` and `conrod`.

**Comment by bluss** [comment]
I gave that a big attempt before picking the current way. There's a lot more traits that G & SG have in common now, though, than before.

**Comment by vilunov** [comment]
Any progress on updating petgraph dependency? Recent std changes made petgraph broken, which was fixed in 0.4.5.

**Comment by azriel91** [comment]
#16 doesn't address the changing indices, it just allows `daggy` to compile.

**Comment by mitchmindtree** [comment]
daggy 0.5.0 was just published which now depends on petgraph 0.4.5, fixing the issue on nightly. I'm going to leave this issue open though as I still think it would still be nice to add a `StableDag` type.

**Comment by davenza** [comment]
I just opened a pull request with an early implementation of the StableDag structure in #21.

**Comment by mitchmindtree** [comment]
Closed via #21.
